ryloth:
  guid: 12
  max_players: 4294967295
  template_name: 10386
  asset_name: Combat_Ryloth_StartingZone_01
  hide_ui: false
  is_combat: true
  chunk_size: 70
  default_point_of_interest:
    guid: 15
    pos:
      x: 598
      y: 9
      z: 669
      w: 1
    rot:
      x: -0.75
      y: 0
      z: -0.67
      w: 0
    name_id: 50654
  speed: 8
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
  map_id: 115
