use crate::game_server::game_packet::GamePacket;
use crate::game_server::player_update_packet::PlayerUpdateOpCode;
use byteorder::{LittleEndian, WriteBytesExt};
use packet_serialize::{SerializePacket, SerializePacketError};
use std::io::Write;

#[derive(Clone, SerializePacket)]
pub struct Item {
    pub definition_id: i32,
    pub tint: i32,
    pub guid: i32,
    pub quantity: i32,
    pub num_consumed: i32,
    pub last_use_time: i32,
    pub market_data: MarketData,
    pub unknown2: bool,
}

#[derive(Clone)]
pub enum MarketData {
    None,
    Some(u64, u32, u32),
}

#[derive(Copy, Clone, Debug)]
pub enum EquipmentSlot {
    None = 0,
    Head = 1,
    Hands = 2,
    Body = 3,
    Feet = 4,
    Shoulders = 5,
    PrimaryWeapon = 7,
    SecondaryWeapon = 8,
    PrimarySaberShape = 10,
    PrimarySaberColor = 11,
    SecondarySaberShape = 12,
    SecondarySaberColor = 13,
    CustomHead = 15,
    CustomHair = 16,
    CustomModel = 17,
    CustomBeard = 18,
}

impl SerializePacket for EquipmentSlot {
    fn serialize(&self, buffer: &mut Vec<u8>) -> Result<(), SerializePacketError> {
        buffer.write_u32::<LittleEndian>(*self as u32)?;
        Ok(())
    }
}

#[derive(Clone, SerializePacket)]
pub struct Unknown41 {}

#[derive(Clone, SerializePacket)]
pub struct Unknown42 {
    unknown1: i32,
    unknown2: i32,
    unknown3: i32,
    unknown4: i32,
    unknown5: i32,
    unknown6: i32,
    unknown7: i32,
}

#[derive(Clone, SerializePacket)]
pub struct ItemDefinition {
    guid: i32,
    name_id: i32,
    description_id: i32,
    icon_set_id: i32,
    icon_tint: i32,
    tint: i32,
    unknown7: i32,
    cost: i32,
    class: i32,
    profile_override: i32,
    slot: EquipmentSlot,
    disable_trade: bool,
    disable_sale: bool,
    model_name: String,
    texture_alias: String,
    gender: i32,
    item_type: i32,
    category: i32,
    members: bool,
    non_minigame: bool,
    unknown21: i32,
    unknown22: i32,
    unknown23: i32,
    unknown24: i32,
    unknown25: i32,
    unknown26: i32,
    unknown27: i32,
    unknown28: bool,
    max_stack_size: i32,
    unknown30: bool,
    unknown31: String,
    unknown32: bool,
    unknown33: bool,
    unknown34: i32,
    unknown35: bool,
    unknown36: i32,
    unknown37: i32,
    unknown38: i32,
    unknown39: i32,
    unknown40: i32,
    unknown41: Vec<Unknown41>,
    unknown42: Vec<Unknown42>,
}

#[derive(SerializePacket)]
pub struct ItemDefinitionsData {
    pub definitions: Vec<ItemDefinition>,
}

pub struct ItemDefinitionsReply {
    pub data: ItemDefinitionsData,
}

impl SerializePacket for ItemDefinitionsReply {
    fn serialize(&self, buffer: &mut Vec<u8>) -> Result<(), SerializePacketError> {
        let mut inner_buffer = Vec::new();
        self.data.serialize(&mut inner_buffer)?;
        buffer.write_u32::<LittleEndian>(inner_buffer.len() as u32)?;
        buffer.write_all(&inner_buffer)?;
        Ok(())
    }
}

impl GamePacket for ItemDefinitionsReply {
    type Header = PlayerUpdateOpCode;
    const HEADER: Self::Header = PlayerUpdateOpCode::ItemDefinitionsReply;
}

pub fn make_item_definitions() -> ItemDefinitionsReply {
    ItemDefinitionsReply {
        data: ItemDefinitionsData {
            definitions: vec![
                ItemDefinition {
                    guid: 1,
                    name_id: 60676,
                    description_id: 0,
                    icon_set_id: 6953,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 1,
                    profile_override: 0,
                    slot: EquipmentSlot::Head,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Wear_Human_<gender>_Head_OfficerCap.adr".to_string(),
                    texture_alias: "OfficerWhite".to_string(),
                    gender: 0,
                    item_type: 1,
                    category: -2,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 2,
                    name_id: 60676,
                    description_id: 0,
                    icon_set_id: 6953,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 1,
                    profile_override: 0,
                    slot: EquipmentSlot::Hands,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Wear_Human_<gender>_Hands_MandalorianSecretServiceGloves.adr"
                        .to_string(),
                    texture_alias: "SecretService".to_string(),
                    gender: 0,
                    item_type: 1,
                    category: -2,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 3,
                    name_id: 60676,
                    description_id: 0,
                    icon_set_id: 6953,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 1,
                    profile_override: 0,
                    slot: EquipmentSlot::Body,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Wear_Human_<gender>_Body_PulsingCrystalSuit.adr".to_string(),
                    texture_alias: "PulsingCrystalBlue".to_string(),
                    gender: 0,
                    item_type: 1,
                    category: -2,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 4,
                    name_id: 60676,
                    description_id: 0,
                    icon_set_id: 6953,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 1,
                    profile_override: 0,
                    slot: EquipmentSlot::Feet,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Wear_Human_<gender>_Feet_CloneBoots.adr".to_string(),
                    texture_alias: "ARCFives".to_string(),
                    gender: 0,
                    item_type: 1,
                    category: -2,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 5,
                    name_id: 2896,
                    description_id: 0,
                    icon_set_id: 2312,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: -1,
                    cost: -1,
                    class: -1,
                    profile_override: 0,
                    slot: EquipmentSlot::PrimaryWeapon,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Wield_Pistol_DC17Chrome.adr".to_string(),
                    texture_alias: "Vigilance".to_string(),
                    gender: -1,
                    item_type: -1,
                    category: -2,
                    members: false,
                    non_minigame: false,
                    unknown21: -1,
                    unknown22: -1,
                    unknown23: -1,
                    unknown24: -1,
                    unknown25: -1,
                    unknown26: -1,
                    unknown27: -1,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: -1,
                    unknown35: false,
                    unknown36: -1,
                    unknown37: -1,
                    unknown38: -1,
                    unknown39: -1,
                    unknown40: -1,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 6,
                    name_id: 0,
                    description_id: 0,
                    icon_set_id: 1756,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 0,
                    profile_override: 0,
                    slot: EquipmentSlot::None,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Furniture_BuildingSetGeneric_Door01.adr".to_string(),
                    texture_alias: "".to_string(),
                    gender: 0,
                    item_type: 29,
                    category: 66,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 7,
                    name_id: 0,
                    description_id: 0,
                    icon_set_id: 0,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 0,
                    profile_override: 0,
                    slot: EquipmentSlot::None,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Furniture_BuildingSetGeneric_Wall01.adr".to_string(),
                    texture_alias: "".to_string(),
                    gender: 0,
                    item_type: 29,
                    category: 66,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: 1000,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 8,
                    name_id: 0,
                    description_id: 0,
                    icon_set_id: 0,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 0,
                    profile_override: 0,
                    slot: EquipmentSlot::None,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Furniture_BuildingSetGeneric_Window01.adr".to_string(),
                    texture_alias: "".to_string(),
                    gender: 0,
                    item_type: 29,
                    category: 66,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: -1,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 9,
                    name_id: 0,
                    description_id: 0,
                    icon_set_id: 0,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 0,
                    profile_override: 0,
                    slot: EquipmentSlot::None,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Furniture_BuildingSetGeneric_Floor01.adr".to_string(),
                    texture_alias: "".to_string(),
                    gender: 0,
                    item_type: 29,
                    category: 66,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: 1000,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
                ItemDefinition {
                    guid: 10,
                    name_id: 0,
                    description_id: 0,
                    icon_set_id: 0,
                    icon_tint: 0,
                    tint: 0,
                    unknown7: 0,
                    cost: 0,
                    class: 0,
                    profile_override: 0,
                    slot: EquipmentSlot::None,
                    disable_trade: false,
                    disable_sale: false,
                    model_name: "Furniture_BuildingSetGeneric_Ceiling01.adr".to_string(),
                    texture_alias: "".to_string(),
                    gender: 0,
                    item_type: 29,
                    category: 66,
                    members: false,
                    non_minigame: false,
                    unknown21: 0,
                    unknown22: 0,
                    unknown23: 0,
                    unknown24: 0,
                    unknown25: 0,
                    unknown26: 0,
                    unknown27: 0,
                    unknown28: false,
                    max_stack_size: 1000,
                    unknown30: false,
                    unknown31: "".to_string(),
                    unknown32: false,
                    unknown33: false,
                    unknown34: 0,
                    unknown35: false,
                    unknown36: 0,
                    unknown37: 0,
                    unknown38: 0,
                    unknown39: 0,
                    unknown40: 0,
                    unknown41: vec![],
                    unknown42: vec![],
                },
            ],
        },
    }
}
