non_world_singleplayer_minigame:
  guid: 200
  max_players: 1
  template_name: 9
  asset_name: Starship_Housing
  hide_ui: false
  is_combat: false
  chunk_size: 1000
  default_point_of_interest:
    guid: 200
    pos:
      x: 244.0913
      y: 10
      z: 465
      w: 1
    rot:
      x: 0
      y: 0
      z: 1.5708
      w: 0
  spawn_sky: sky_starship_default.xml
  speed: 8
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
  update_previous_location_on_leave: false
non_world_two_player_minigame:
  guid: 201
  max_players: 2
  template_name: 9
  asset_name: Starship_Housing
  hide_ui: false
  is_combat: false
  chunk_size: 1000
  default_point_of_interest:
    guid: 201
    pos:
      x: 244.0913
      y: 10
      z: 465
      w: 1
    rot:
      x: 0
      y: 0
      z: 1.5708
      w: 0
  spawn_sky: sky_starship_default.xml
  speed: 8
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
  update_previous_location_on_leave: false
