---
jedi_temple:
  ambient_npcs:
    halloween_decorations_veranda:
      model_id: 94
      head_customization_override: Events_Halloween_JediTemple_Veranda_Group_01.adr
      enable_gravity: false
      pos:
        x: 916.0
        y: 150.0
        z: 1563.0
        w: 1.0
      rot:
        x: -1
        y: 0
        z: 0
        w: 0
      enable_camera_clipping: true
      tickable_procedures: &halloween_tickable_procedures
        spawn:
          steps:
            - spawned_state: Always
              min_duration_millis: 1
          next_possible_procedures:
            - procedure: spawn
        despawn:
          steps:
            - spawned_state: Despawn
              min_duration_millis: 1
          next_possible_procedures:
            - procedure: despawn
      first_possible_procedures: &halloween_first_possible_procedures [despawn]
      scheduled_procedures: &halloween_scheduled_procedures
        - schedule: "* * * * 10 *"
          possible_procedures:
            - procedure: spawn
        - schedule: "* * * * 1-9,11-12 *"
          possible_procedures:
            - procedure: despawn
