---
# Primary abilities
plo_koon_lightsaber:
  slot_info:
    icon_set_id: 232
    name_id: 60026

dahgee_jedi_lightsaber:
  slot_info:
    icon_set_id: 1148
    name_id: 60026

ahsoka_tano_reverse_lightsaber:
  slot_info:
    icon_set_id: 220
    name_id: 60026

anakin_skywalker_lightsaber:
  slot_info:
    icon_set_id: 223
    name_id: 60026

zabrak_sith_lightsaber:
  slot_info:
    icon_set_id: 219
    name_id: 60026

adi_gallia_lightsaber:
  slot_info:
    icon_set_id: 222
    name_id: 60026

pre_vizsla_darksaber:
  slot_info:
    icon_set_id: 224
    name_id: 60026

count_dooku_lightsaber:
  slot_info:
    icon_set_id: 225
    name_id: 60026

kit_fisto_lightsaber:
  slot_info:
    icon_set_id: 229
    name_id: 60026

luminara_unduli_lightsaber:
  slot_info:
    icon_set_id: 231
    name_id: 60026

mace_windu_lightsaber:
  slot_info:
    icon_set_id: 233
    name_id: 60026

obi_wan_kenobi_lightsaber:
  slot_info:
    icon_set_id: 234
    name_id: 60026

darth_sidious_lightsaber:
  slot_info:
    icon_set_id: 235
    name_id: 60026

training_lightsaber:
  slot_info:
    icon_set_id: 236
    name_id: 60026

asajj_ventress_right_lightsaber:
  slot_info:
    icon_set_id: 237
    name_id: 60026

miko_jedi_lightsaber:
  slot_info:
    icon_set_id: 509
    name_id: 60026

mestare_lightsaber:
  slot_info:
    icon_set_id: 510
    name_id: 60026

shaak_ti_lightsaber:
  slot_info:
    icon_set_id: 513
    name_id: 60026

savek_lightsaber:
  slot_info:
    icon_set_id: 517
    name_id: 60026

kyle_katarn_lightsaber:
  slot_info:
    icon_set_id: 511
    name_id: 60026

shotem_jedi_lightsaber:
  slot_info:
    icon_set_id: 512
    name_id: 60026

bravis_sith_lightsaber:
  slot_info:
    icon_set_id: 514
    name_id: 60026

ermi_jedi_lightsaber:
  slot_info:
    icon_set_id: 515
    name_id: 60026

ancient_cobal_lightsaber:
  slot_info:
    icon_set_id: 516
    name_id: 60026

ultimate_fx_gungan_lightsaber:
  slot_info:
    icon_set_id: 2136
    name_id: 60026

quinlan_vos_lightsaber:
  slot_info:
    icon_set_id: 1436
    name_id: 60026

ahsoka_tano_lightsaber:
  slot_info:
    icon_set_id: 1459
    name_id: 60026

savage_opress_lightsaber:
  slot_info:
    icon_set_id: 1656
    name_id: 60026

saesee_tiin_lightsaber:
  slot_info:
    icon_set_id: 1792
    name_id: 60026

kashyyyk_lightsaber:
  slot_info:
    icon_set_id: 1993
    name_id: 60026

sith_marauder_lightsaber:
  slot_info:
    icon_set_id: 3044
    name_id: 60026

nelona_lightsaber:
  slot_info:
    icon_set_id: 2838
    name_id: 60026

sith_warrior_lightsaber:
  slot_info:
    icon_set_id: 3118
    name_id: 60026

sith_inquisitor_lightsaber:
  slot_info:
    icon_set_id: 2938
    name_id: 60026

forgotten_jedi_reverse_lightsaber:
  slot_info:
    icon_set_id: 3735
    name_id: 60026

jedi_champion_reverse_lightsaber:
  slot_info:
    icon_set_id: 3133
    name_id: 60026

kofun_lightsaber:
  slot_info:
    icon_set_id: 2862
    name_id: 60026

aayla_secura_lightsaber:
  slot_info:
    icon_set_id: 221
    name_id: 60026

barriss_offee_lightsaber:
  slot_info:
    icon_set_id: 508
    name_id: 60026

byph_lightsaber:
  slot_info:
    icon_set_id: 3207
    name_id: 60026

sith_infiltrator_lightsaber:
  slot_info:
    icon_set_id: 3045
    name_id: 60026

dolovite_darksaber:
  slot_info:
    icon_set_id: 3829
    name_id: 60026

phrik_darksaber:
  slot_info:
    icon_set_id: 3791
    name_id: 60026

darth_maul_lightsaber:
  slot_info:
    icon_set_id: 2764
    name_id: 60026

eeth_koth_lightsaber:
  slot_info:
    icon_set_id: 226
    name_id: 60026

jedi_exile_lightsaber:
  slot_info:
    icon_set_id: 3835
    name_id: 60026

forked_lightsaber:
  slot_info:
    icon_set_id: 3828
    name_id: 60026

ganodi_lightsaber:
  slot_info:
    icon_set_id: 3212
    name_id: 60026

gungi_lightsaber:
  slot_info:
    icon_set_id: 3208
    name_id: 60026

jocasta_nu_lightsaber:
  slot_info:
    icon_set_id: 227
    name_id: 60026

katooni_lightsaber:
  slot_info:
    icon_set_id: 3213
    name_id: 60026

ki_adi_mundi_lightsaber:
  slot_info:
    icon_set_id: 228
    name_id: 60026

sulon_jedi_lightsaber:
  slot_info:
    icon_set_id: 511
    name_id: 60026

luke_skywalker_lightsaber:
  slot_info:
    icon_set_id: 230
    name_id: 60026

petro_lightsaber:
  slot_info:
    icon_set_id: 3209
    name_id: 60026

shotem_master_lightsaber:
  slot_info:
    icon_set_id: 3788
    name_id: 60026

crimson_prowler_lightsaber:
  slot_info:
    icon_set_id: 3721
    name_id: 60026

talz_lightsaber:
  slot_info:
    icon_set_id: 2863
    name_id: 60026

yoda_lightsaber:
  slot_info:
    icon_set_id: 3169
    name_id: 60026

zatt_lightsaber:
  slot_info:
    icon_set_id: 3211
    name_id: 60026

pink_gaffi_stick:
  slot_info:
    icon_set_id: 518
    name_id: 60026

blinged_out_trooper_rifle:
  slot_info:
    icon_set_id: 239
    name_id: 60026

clone_trooper_blaster:
  slot_info:
    icon_set_id: 213
    name_id: 60026

boba_fett_blaster_rifle:
  slot_info:
    icon_set_id: 215
    name_id: 60026

naboo_security_blaster_pistol:
  slot_info:
    icon_set_id: 250
    name_id: 60026

gaffi_stick:
  slot_info:
    icon_set_id: 253
    name_id: 60026

clone_trooper_blaster_rifle:
  slot_info:
    icon_set_id: 240
    name_id: 60026

cad_bane_right_blaster:
  slot_info:
    icon_set_id: 248
    name_id: 60026

aurra_sing_hunting_rifle:
  slot_info:
    icon_set_id: 238
    name_id: 60026

captain_rex_right_blaster:
  slot_info:
    icon_set_id: 244
    name_id: 60026

han_solo_blaster_pistol:
  slot_info:
    icon_set_id: 246
    name_id: 60026

republic_flamethrower:
  slot_info:
    icon_set_id: 216
    name_id: 60026

republic_missile_launcher:
  slot_info:
    icon_set_id: 218
    name_id: 60026

rotary_blaster_cannon:
  slot_info:
    icon_set_id: 217
    name_id: 60026

mandalorian_blaster_rifle:
  slot_info:
    icon_set_id: 507
    name_id: 60026

bowcaster:
  slot_info:
    icon_set_id: 506
    name_id: 60026

papanoida_blaster:
  slot_info:
    icon_set_id: 1327
    name_id: 60026

assassin_aurra_sing_right_blaster:
  slot_info:
    icon_set_id: 1409
    name_id: 60026

satine_royal_guard_staff:
  slot_info:
    icon_set_id: 251
    name_id: 60026

gungan_double_headed_spear:
  slot_info:
    icon_set_id: 2337
    name_id: 60026

spring_fever:
  slot_info:
    icon_set_id: 1935
    name_id: 60026

balnab_hunter_rifle:
  slot_info:
    icon_set_id: 2391
    name_id: 60026

nightsister_bow:
  slot_info:
    icon_set_id: 1624
    name_id: 60026

savage_opress_pike:
  slot_info:
    icon_set_id: 1632
    name_id: 60026

cupid_clone_bow:
  slot_info:
    icon_set_id: 1674
    name_id: 60026

blue_sparkler:
  slot_info:
    icon_set_id: 2001
    name_id: 60026

green_sparkler:
  slot_info:
    icon_set_id: 2002
    name_id: 60026

orange_sparkler:
  slot_info:
    icon_set_id: 2003
    name_id: 60026

purple_sparkler:
  slot_info:
    icon_set_id: 2004
    name_id: 60026

red_sparkler:
  slot_info:
    icon_set_id: 2005
    name_id: 60026

white_sparkler:
  slot_info:
    icon_set_id: 2006
    name_id: 60026

yellow_sparkler:
  slot_info:
    icon_set_id: 2007
    name_id: 60026

vigilance:
  slot_info:
    icon_set_id: 2312
    name_id: 60026

skeletal_clone_trooper_scythe:
  slot_info:
    icon_set_id: 2399
    name_id: 60026

umbaran_blaster_rifle:
  slot_info:
    icon_set_id: 2448
    name_id: 60026

zygerrian_blaster_rifle:
  slot_info:
    icon_set_id: 2513
    name_id: 60026

captain_rex_zygerrian_electrostaff:
  slot_info:
    icon_set_id: 2518
    name_id: 60026

shadow_tech_rifle:
  slot_info:
    icon_set_id: 2571
    name_id: 60026

rako_hardeen_sniper_rifle:
  slot_info:
    icon_set_id: 2659
    name_id: 60026

cad_bane_blaster_rifle:
  slot_info:
    icon_set_id: 2654
    name_id: 60026

cryo_cannon:
  slot_info:
    icon_set_id: 2678
    name_id: 60026

plasma_thrower:
  slot_info:
    icon_set_id: 2679
    name_id: 60026

ion_blaster:
  slot_info:
    icon_set_id: 2680
    name_id: 60026

quarzite_boba_fett_blaster:
  slot_info:
    icon_set_id: 2734
    name_id: 60026

cold_warrior_rifle:
  slot_info:
    icon_set_id: 2976
    name_id: 60026

ming_po_militia_rifle:
  slot_info:
    icon_set_id: 3085
    name_id: 60026

usk_bunker_general_blaster_rifle:
  slot_info:
    icon_set_id: 2819
    name_id: 60026

grek_bunker_general_blaster_rifle:
  slot_info:
    icon_set_id: 2815
    name_id: 60026

republic_grenade_launcher:
  slot_info:
    icon_set_id: 2809
    name_id: 60026

accelerated_thermal_carbine:
  slot_info:
    icon_set_id: 2882
    name_id: 60026

rail_cannon:
  slot_info:
    icon_set_id: 3771
    name_id: 60026

hip_mounted_cannon:
  slot_info:
    icon_set_id: 2810
    name_id: 60026

mandalorian_repeater:
  slot_info:
    icon_set_id: 3790
    name_id: 60026

repeater_cannon:
  slot_info:
    icon_set_id: 3827
    name_id: 60026

turbolaser:
  slot_info:
    icon_set_id: 2811
    name_id: 60026

bossk_long_rifle:
  slot_info:
    icon_set_id: 2789
    name_id: 60026

grand_officer_rifle:
  slot_info:
    icon_set_id: 3108
    name_id: 60026

felucian_commando_rifle:
  slot_info:
    icon_set_id: 3726
    name_id: 60026

onderon_long_rifle:
  slot_info:
    icon_set_id: 3158
    name_id: 60026

energized_disruptor:
  slot_info:
    icon_set_id: 2680
    name_id: 60026

light_plasma_pistol:
  slot_info:
    icon_set_id: 2925
    name_id: 60026

major_rigosso_quarzite_pistol:
  slot_info:
    icon_set_id: 2808
    name_id: 60026

black_sun_blaster_pistol:
  slot_info:
    icon_set_id: 3637
    name_id: 60026

subtram_hunter_blaster:
  slot_info:
    icon_set_id: 3783
    name_id: 60026

royal_hold_out_blaster_pistol:
  slot_info:
    icon_set_id: 247
    name_id: 60026

corrupt_warlord_right_pistol:
  slot_info:
    icon_set_id: 3143
    name_id: 60026

pyke_blaster_pistol:
  slot_info:
    icon_set_id: 3638
    name_id: 60026

onderon_blaster_pistol:
  slot_info:
    icon_set_id: 3159
    name_id: 60026

ig_113_electrostaff:
  slot_info:
    icon_set_id: 3002
    name_id: 60026

renegade_heavy_blaster_pistol_right:
  slot_info:
    icon_set_id: 3792
    name_id: 60026

# Secondary Abilities
force_push:
  slot_info:
    icon_set_id: 3175
    name_id: 50564

force_valor:
  slot_info:
    icon_set_id: 3176
    name_id: 53516

force_lightning:
  slot_info:
    icon_set_id: 3174
    name_id: 10641

force_heal:
  slot_info:
    icon_set_id: 3173
    name_id: 53518

emerald_lightning:
  slot_info:
    icon_set_id: 3174
    name_id: 53664

force_drain:
  slot_info:
    icon_set_id: 3287
    name_id: 53636

thermal_grenade:
  slot_info:
    icon_set_id: 3179
    name_id: 7

deflector_shield:
  slot_info:
    icon_set_id: 3178
    name_id: 52684

proximity_mine:
  slot_info:
    icon_set_id: 3177
    name_id: 53514

cryo_grenade:
  slot_info:
    icon_set_id: 3286
    name_id: 18103

deploy_turret:
  slot_info:
    icon_set_id: 3288
    name_id: 54056

# Tertiary abilities
slashing_strike:
  slot_info:
    icon_set_id: 3752
    name_id: 60321

chopping_lunge:
  slot_info:
    icon_set_id: 3752
    name_id: 60321

aimed_shot:
  slot_info:
    icon_set_id: 3750
    name_id: 60324

focused_shot:
  slot_info:
    icon_set_id: 3754
    name_id: 60323

charged_shot:
  slot_info:
    icon_set_id: 3751
    name_id: 60327

rapid_fire:
  slot_info:
    icon_set_id: 3755
    name_id: 60326
