---
# Primary Abilities
- ability_key: "Plo Koon's Lightsaber"
  slot_info:
    icon_set_id: 232
    name_id: 60026

- ability_key: "Dahgee Jedi Lightsaber"
  slot_info:
    icon_set_id: 1148
    name_id: 60026

- ability_key: "Ahsoka Tano's Reverse Lightsaber"
  slot_info:
    icon_set_id: 220
    name_id: 60026

- ability_key: "Anakin Skywalker's Lightsaber"
  slot_info:
    icon_set_id: 223
    name_id: 60026

- ability_key: "Zabrak Sith Lightsaber"
  slot_info:
    icon_set_id: 219
    name_id: 60026

- ability_key: "Adi Gallia's Lightsaber"
  slot_info:
    icon_set_id: 222
    name_id: 60026

- ability_key: "Pre Vizsla's Darksaber"
  slot_info:
    icon_set_id: 224
    name_id: 60026

- ability_key: "Count Dooku's Lightsaber"
  slot_info:
    icon_set_id: 225
    name_id: 60026

- ability_key: "Kit Fisto's Lightsaber"
  slot_info:
    icon_set_id: 229
    name_id: 60026

- ability_key: "Luminara Unduli's Lightsaber"
  slot_info:
    icon_set_id: 231
    name_id: 60026

- ability_key: "Mace Windu's Lightsaber"
  slot_info:
    icon_set_id: 233
    name_id: 60026

- ability_key: "Obi-Wan Kenobi's Lightsaber"
  slot_info:
    icon_set_id: 234
    name_id: 60026

- ability_key: "Darth Sidious' Lightsaber"
  slot_info:
    icon_set_id: 235
    name_id: 60026

- ability_key: "Training Lightsaber"
  slot_info:
    icon_set_id: 236
    name_id: 60026

- ability_key: "Asajj Ventress' Right Lightsaber"
  slot_info:
    icon_set_id: 237
    name_id: 60026

- ability_key: "Miko Jedi Lightsaber"
  slot_info:
    icon_set_id: 509
    name_id: 60026

- ability_key: "Mestare Lightsaber"
  slot_info:
    icon_set_id: 510
    name_id: 60026

- ability_key: "Shaak Ti's Lightsaber"
  slot_info:
    icon_set_id: 513
    name_id: 60026

- ability_key: "Savek Lightsaber"
  slot_info:
    icon_set_id: 517
    name_id: 60026

- ability_key: "Kyle Katarn's Lightsaber"
  slot_info:
    icon_set_id: 511
    name_id: 60026

- ability_key: "Shotem Jedi Lightsaber"
  slot_info:
    icon_set_id: 512
    name_id: 60026

- ability_key: "Bravis Sith Lightsaber"
  slot_info:
    icon_set_id: 514
    name_id: 60026

- ability_key: "Ermi Jedi Lightsaber"
  slot_info:
    icon_set_id: 515
    name_id: 60026

- ability_key: "Ancient Cobal Lightsaber"
  slot_info:
    icon_set_id: 516
    name_id: 60026

- ability_key: "Ultimate FX Gungan Lightsaber"
  slot_info:
    icon_set_id: 2136
    name_id: 60026

- ability_key: "Quinlan Vos' Lightsaber"
  slot_info:
    icon_set_id: 1436
    name_id: 60026

- ability_key: "Ahsoka Tano's Lightsaber"
  slot_info:
    icon_set_id: 1459
    name_id: 60026

- ability_key: "Savage Opress' Lightsaber"
  slot_info:
    icon_set_id: 1656
    name_id: 60026

- ability_key: "Saesee Tiin's Lightsaber"
  slot_info:
    icon_set_id: 1792
    name_id: 60026

- ability_key: "Kashyyyk Lightsaber"
  slot_info:
    icon_set_id: 1993
    name_id: 60026

- ability_key: "Sith Marauder Lightsaber"
  slot_info:
    icon_set_id: 3044
    name_id: 60026

- ability_key: "Nelona Lightsaber"
  slot_info:
    icon_set_id: 2838
    name_id: 60026

- ability_key: "Sith Warrior Lightsaber"
  slot_info:
    icon_set_id: 3118
    name_id: 60026

- ability_key: "Sith Inquisitor Lightsaber"
  slot_info:
    icon_set_id: 2938
    name_id: 60026

- ability_key: "Forgotten Jedi Reverse Lightsaber"
  slot_info:
    icon_set_id: 3735
    name_id: 60026

- ability_key: "Jedi Champion Reverse Lightsaber"
  slot_info:
    icon_set_id: 3133
    name_id: 60026

- ability_key: "Kofun Lightsaber"
  slot_info:
    icon_set_id: 2862
    name_id: 60026

- ability_key: "Aayla Secura's Lightsaber"
  slot_info:
    icon_set_id: 221
    name_id: 60026

- ability_key: "Barriss Offee's Lightsaber"
  slot_info:
    icon_set_id: 508
    name_id: 60026

- ability_key: "Byph's Lightsaber"
  slot_info:
    icon_set_id: 3207
    name_id: 60026

- ability_key: "Sith Infiltrator Lightsaber"
  slot_info:
    icon_set_id: 3045
    name_id: 60026

- ability_key: "Dolovite Darksaber"
  slot_info:
    icon_set_id: 3829
    name_id: 60026

- ability_key: "Phrik Darksaber"
  slot_info:
    icon_set_id: 3791
    name_id: 60026

- ability_key: "Darth Maul's Lightsaber"
  slot_info:
    icon_set_id: 2764
    name_id: 60026

- ability_key: "Eeth Koth's Lightsaber"
  slot_info:
    icon_set_id: 226
    name_id: 60026

- ability_key: "Jedi Exile Lightsaber"
  slot_info:
    icon_set_id: 3835
    name_id: 60026

- ability_key: "Forked Lightsaber"
  slot_info:
    icon_set_id: 3828
    name_id: 60026

- ability_key: "Ganodi's Lightsaber"
  slot_info:
    icon_set_id: 3212
    name_id: 60026

- ability_key: "Gungi's Lightsaber"
  slot_info:
    icon_set_id: 3208
    name_id: 60026

- ability_key: "Jocasta Nu's Lightsaber"
  slot_info:
    icon_set_id: 227
    name_id: 60026

- ability_key: "Katooni's Lightsaber"
  slot_info:
    icon_set_id: 3213
    name_id: 60026

- ability_key: "Ki-Adi-Mundi's Lightsaber"
  slot_info:
    icon_set_id: 228
    name_id: 60026

- ability_key: "Sulon Jedi Lightsaber"
  slot_info:
    icon_set_id: 511
    name_id: 60026

- ability_key: "Luke Skywalker's Lightsaber"
  slot_info:
    icon_set_id: 230
    name_id: 60026

- ability_key: "Petro's Lightsaber"
  slot_info:
    icon_set_id: 3209
    name_id: 60026

- ability_key: "Shotem Master Lightsaber"
  slot_info:
    icon_set_id: 3788
    name_id: 60026

- ability_key: "Crimson Prowler Lightsaber"
  slot_info:
    icon_set_id: 3721
    name_id: 60026

- ability_key: "Talz Lightsaber"
  slot_info:
    icon_set_id: 2863
    name_id: 60026

- ability_key: "Yoda's Lightsaber"
  slot_info:
    icon_set_id: 3169
    name_id: 60026

- ability_key: "Zatt's Lightsaber"
  slot_info:
    icon_set_id: 3211
    name_id: 60026

- ability_key: "Pink Gaffi Stick"
  slot_info:
    icon_set_id: 518
    name_id: 60026

- ability_key: "Blinged-Out Trooper Rifle"
  slot_info:
    icon_set_id: 239
    name_id: 60026

- ability_key: "Clone Trooper Blaster"
  slot_info:
    icon_set_id: 213
    name_id: 60026

- ability_key: "Boba Fett's Blaster Rifle"
  slot_info:
    icon_set_id: 215
    name_id: 60026

- ability_key: "Naboo Security Blaster Pistol"
  slot_info:
    icon_set_id: 250
    name_id: 60026

- ability_key: "Gaffi Stick"
  slot_info:
    icon_set_id: 253
    name_id: 60026

- ability_key: "Clone Trooper Blaster Rifle"
  slot_info:
    icon_set_id: 240
    name_id: 60026

- ability_key: "Cad Bane's Right Blaster"
  slot_info:
    icon_set_id: 248
    name_id: 60026

- ability_key: "Aurra Sing's Hunting Rifle"
  slot_info:
    icon_set_id: 238
    name_id: 60026

- ability_key: "Captain Rex's Right Blaster"
  slot_info:
    icon_set_id: 244
    name_id: 60026

- ability_key: "Han Solo's Blaster Pistol"
  slot_info:
    icon_set_id: 246
    name_id: 60026

- ability_key: "Republic Flamethrower"
  slot_info:
    icon_set_id: 216
    name_id: 60026

- ability_key: "Republic Missile Launcher"
  slot_info:
    icon_set_id: 218
    name_id: 60026

- ability_key: "Rotary Blaster Cannon"
  slot_info:
    icon_set_id: 217
    name_id: 60026

- ability_key: "Mandalorian Blaster Rifle"
  slot_info:
    icon_set_id: 507
    name_id: 60026

- ability_key: "Bowcaster"
  slot_info:
    icon_set_id: 506
    name_id: 60026

- ability_key: "Papanoida Blaster"
  slot_info:
    icon_set_id: 1327
    name_id: 60026

- ability_key: "Assassin Aurra Sing's Right Blaster"
  slot_info:
    icon_set_id: 1409
    name_id: 60026

- ability_key: "Satine's Royal Guard Staff"
  slot_info:
    icon_set_id: 251
    name_id: 60026

- ability_key: "Gungan Double-headed Spear"
  slot_info:
    icon_set_id: 2337
    name_id: 60026

- ability_key: "Spring Fever"
  slot_info:
    icon_set_id: 1935
    name_id: 60026

- ability_key: "Balnab Hunter Rifle"
  slot_info:
    icon_set_id: 2391
    name_id: 60026

- ability_key: "Nightsister's Bow"
  slot_info:
    icon_set_id: 1624
    name_id: 60026

- ability_key: "Savage Opress' Pike"
  slot_info:
    icon_set_id: 1632
    name_id: 60026

- ability_key: "Cupid Clone's Bow"
  slot_info:
    icon_set_id: 1674
    name_id: 60026

- ability_key: "Blue Sparkler"
  slot_info:
    icon_set_id: 2001
    name_id: 60026

- ability_key: "Green Sparkler"
  slot_info:
    icon_set_id: 2002
    name_id: 60026

- ability_key: "Orange Sparkler"
  slot_info:
    icon_set_id: 2003
    name_id: 60026

- ability_key: "Purple Sparkler"
  slot_info:
    icon_set_id: 2004
    name_id: 60026

- ability_key: "Red Sparkler"
  slot_info:
    icon_set_id: 2005
    name_id: 60026

- ability_key: "White Sparkler"
  slot_info:
    icon_set_id: 2006
    name_id: 60026

- ability_key: "Yellow Sparkler"
  slot_info:
    icon_set_id: 2007
    name_id: 60026

- ability_key: "Vigilance"
  slot_info:
    icon_set_id: 2312
    name_id: 60026

- ability_key: "Skeletal Clone Trooper Scythe"
  slot_info:
    icon_set_id: 2399
    name_id: 60026

- ability_key: "Umbaran Blaster Rifle"
  slot_info:
    icon_set_id: 2448
    name_id: 60026

- ability_key: "Zygerrian Blaster Rifle"
  slot_info:
    icon_set_id: 2513
    name_id: 60026

- ability_key: "Captain Rex's Zygerrian Electrostaff"
  slot_info:
    icon_set_id: 2518
    name_id: 60026

- ability_key: "Shadow Tech Rifle"
  slot_info:
    icon_set_id: 2571
    name_id: 60026

- ability_key: "Rako Hardeen's Sniper Rifle"
  slot_info:
    icon_set_id: 2659
    name_id: 60026

- ability_key: "Cad Bane's Blaster Rifle"
  slot_info:
    icon_set_id: 2654
    name_id: 60026

- ability_key: "Cryo-Cannon"
  slot_info:
    icon_set_id: 2678
    name_id: 60026

- ability_key: "Plasma Thrower"
  slot_info:
    icon_set_id: 2679
    name_id: 60026

- ability_key: "Ion Blaster"
  slot_info:
    icon_set_id: 2680
    name_id: 60026

- ability_key: "Quarzite Boba Fett's Blaster"
  slot_info:
    icon_set_id: 2734
    name_id: 60026

- ability_key: "Cold Warrior Rifle"
  slot_info:
    icon_set_id: 2976
    name_id: 60026

- ability_key: "Ming Po Militia Rifle"
  slot_info:
    icon_set_id: 3085
    name_id: 60026

- ability_key: "Usk Bunker General Blaster Rifle"
  slot_info:
    icon_set_id: 2819
    name_id: 60026

- ability_key: "Grek Bunker General Blaster Rifle"
  slot_info:
    icon_set_id: 2815
    name_id: 60026

- ability_key: "Republic Grenade Launcher"
  slot_info:
    icon_set_id: 2809
    name_id: 60026

- ability_key: "Accelerated Thermal Carbine"
  slot_info:
    icon_set_id: 2882
    name_id: 60026

- ability_key: "Rail Cannon"
  slot_info:
    icon_set_id: 3771
    name_id: 60026

- ability_key: "Hip-Mounted Cannon"
  slot_info:
    icon_set_id: 2810
    name_id: 60026

- ability_key: "Mandalorian Repeater"
  slot_info:
    icon_set_id: 3790
    name_id: 60026

- ability_key: "Repeater Cannon"
  slot_info:
    icon_set_id: 3827
    name_id: 60026

- ability_key: "Turbolaser"
  slot_info:
    icon_set_id: 2811
    name_id: 60026

- ability_key: "Bossk's Long Rifle"
  slot_info:
    icon_set_id: 2789
    name_id: 60026

- ability_key: "Grand Officer Rifle"
  slot_info:
    icon_set_id: 3108
    name_id: 60026

- ability_key: "Felucian Commando Rifle"
  slot_info:
    icon_set_id: 3726
    name_id: 60026

- ability_key: "Onderon Long Rifle"
  slot_info:
    icon_set_id: 3158
    name_id: 60026

- ability_key: "Energized Disruptor"
  slot_info:
    icon_set_id: 2680
    name_id: 60026

- ability_key: "Light Plasma Pistol"
  slot_info:
    icon_set_id: 2925
    name_id: 60026

- ability_key: "Major Rigosso's Quarzite Pistol"
  slot_info:
    icon_set_id: 2808
    name_id: 60026

- ability_key: "Black Sun Blaster Pistol"
  slot_info:
    icon_set_id: 3637
    name_id: 60026

- ability_key: "Subtram Hunter Blaster"
  slot_info:
    icon_set_id: 3783
    name_id: 60026

- ability_key: "Royal Hold-out Blaster Pistol"
  slot_info:
    icon_set_id: 247
    name_id: 60026

- ability_key: "Corrupt Warlord Right Pistol"
  slot_info:
    icon_set_id: 3143
    name_id: 60026

- ability_key: "Pyke Blaster Pistol"
  slot_info:
    icon_set_id: 3638
    name_id: 60026

- ability_key: "Onderon Blaster Pistol"
  slot_info:
    icon_set_id: 3159
    name_id: 60026

- ability_key: "IG-113's Electrostaff"
  slot_info:
    icon_set_id: 3002
    name_id: 60026

- ability_key: "Renegade Heavy Blaster Pistol (Right)"
  slot_info:
    icon_set_id: 3792
    name_id: 60026

# Secondary Abilities
- ability_key: "Force Push"
  slot_info:
    icon_set_id: 3175
    name_id: 50564

- ability_key: "Force Valor"
  slot_info:
    icon_set_id: 3176
    name_id: 53516

- ability_key: "Force Lightning"
  slot_info:
    icon_set_id: 3174
    name_id: 10641

- ability_key: "Force Heal"
  slot_info:
    icon_set_id: 3173
    name_id: 53518

- ability_key: "Emerald Lightning"
  slot_info:
    icon_set_id: 3174
    name_id: 53664

- ability_key: "Force Drain"
  slot_info:
    icon_set_id: 3287
    name_id: 53636

- ability_key: "Thermal Grenade"
  slot_info:
    icon_set_id: 3179
    name_id: 7

- ability_key: "Deflector Shield"
  slot_info:
    icon_set_id: 3178
    name_id: 52684

- ability_key: "Proximity Mine"
  slot_info:
    icon_set_id: 3177
    name_id: 53514

- ability_key: "Cryo Grenade"
  slot_info:
    icon_set_id: 3286
    name_id: 18103

- ability_key: "Deploy Turret"
  slot_info:
    icon_set_id: 3288
    name_id: 54056

# Tertiary abilities
- ability_key: "Slashing Strike"
  slot_info:
    icon_set_id: 3752
    name_id: 60321

- ability_key: "Chopping Lunge"
  slot_info:
    icon_set_id: 3752
    name_id: 60321

- ability_key: "Aimed Shot"
  slot_info:
    icon_set_id: 3750
    name_id: 60324

- ability_key: "Focused Shot"
  slot_info:
    icon_set_id: 3754
    name_id: 60323

- ability_key: "Charged Shot"
  slot_info:
    icon_set_id: 3751
    name_id: 60327

- ability_key: "Rapid Fire"
  slot_info:
    icon_set_id: 3755
    name_id: 60326
