---
- hilt_item_guid: 63
  shape_item_guid: 90000
  color_item_guid: 100003
- hilt_item_guid: 227
  shape_item_guid: 90019
  color_item_guid: 100001
- hilt_item_guid: 300
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 422
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 435
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 437
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 526
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 527
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 528
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 532
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 534
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 535
  shape_item_guid: 90000
  color_item_guid: 100005
- hilt_item_guid: 536
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 537
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 538
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 539
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 761
  shape_item_guid: 90004
  color_item_guid: 100009
- hilt_item_guid: 762
  shape_item_guid: 90013
  color_item_guid: 100006
- hilt_item_guid: 763
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 764
  shape_item_guid: 90009
  color_item_guid: 100004
- hilt_item_guid: 786
  shape_item_guid: 90015
  color_item_guid: 100002
- hilt_item_guid: 787
  shape_item_guid: 90005
  color_item_guid: 100002
- hilt_item_guid: 788
  shape_item_guid: 90007
  color_item_guid: 100004
- hilt_item_guid: 789
  shape_item_guid: 90008
  color_item_guid: 100001
- hilt_item_guid: 790
  shape_item_guid: 90003
  color_item_guid: 100007
- hilt_item_guid: 1992
  shape_item_guid: 90012
  color_item_guid: 100005
- hilt_item_guid: 2134
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 2140
  shape_item_guid: 120014
  color_item_guid: 130001
- hilt_item_guid: 2141
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 2363
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 2708
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 2801
  shape_item_guid: 90010
  color_item_guid: 100001
- hilt_item_guid: 110000
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110001
  shape_item_guid: 90000
  color_item_guid: 100009
- hilt_item_guid: 110002
  shape_item_guid: 90018
  color_item_guid: 100012
- hilt_item_guid: 110003
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110004
  shape_item_guid: 90006
  color_item_guid: 100006
- hilt_item_guid: 110005
  shape_item_guid: 90016
  color_item_guid: 100001
- hilt_item_guid: 110006
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 110007
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110008
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110009
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110010
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 110011
  shape_item_guid: 90001
  color_item_guid: 100010
- hilt_item_guid: 110012
  shape_item_guid: 90002
  color_item_guid: 100001
- hilt_item_guid: 110013
  shape_item_guid: 90000
  color_item_guid: 100012
- hilt_item_guid: 110014
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110015
  shape_item_guid: 90000
  color_item_guid: 100002
- hilt_item_guid: 110016
  shape_item_guid: 90011
  color_item_guid: 100001
- hilt_item_guid: 110017
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110018
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110019
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110020
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110021
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110022
  shape_item_guid: 90015
  color_item_guid: 100000
- hilt_item_guid: 110023
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 110024
  shape_item_guid: 90000
  color_item_guid: 100000
- hilt_item_guid: 110025
  shape_item_guid: 90005
  color_item_guid: 100000
- hilt_item_guid: 110026
  shape_item_guid: 90007
  color_item_guid: 100012
- hilt_item_guid: 110027
  shape_item_guid: 90009
  color_item_guid: 100007
- hilt_item_guid: 110028
  shape_item_guid: 90014
  color_item_guid: 100001
- hilt_item_guid: 110029
  shape_item_guid: 90000
  color_item_guid: 100001
- hilt_item_guid: 140000
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140001
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140002
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140003
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140004
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140005
  shape_item_guid: 120004
  color_item_guid: 130009
- hilt_item_guid: 140006
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140007
  shape_item_guid: 120001
  color_item_guid: 130010
- hilt_item_guid: 140008
  shape_item_guid: 120001
  color_item_guid: 130010
- hilt_item_guid: 140009
  shape_item_guid: 120002
  color_item_guid: 130001
- hilt_item_guid: 140010
  shape_item_guid: 120000
  color_item_guid: 130012
- hilt_item_guid: 140011
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140012
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140013
  shape_item_guid: 120000
  color_item_guid: 130002
- hilt_item_guid: 140014
  shape_item_guid: 120011
  color_item_guid: 130001
- hilt_item_guid: 140015
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140016
  shape_item_guid: 120012
  color_item_guid: 130005
- hilt_item_guid: 140017
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140018
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140019
  shape_item_guid: 120010
  color_item_guid: 130001
- hilt_item_guid: 140020
  shape_item_guid: 120013
  color_item_guid: 130006
- hilt_item_guid: 140021
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140022
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140023
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140024
  shape_item_guid: 120015
  color_item_guid: 130002
- hilt_item_guid: 140025
  shape_item_guid: 120015
  color_item_guid: 130000
- hilt_item_guid: 140026
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140027
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140028
  shape_item_guid: 120000
  color_item_guid: 130003
- hilt_item_guid: 140029
  shape_item_guid: 120000
  color_item_guid: 130005
- hilt_item_guid: 140030
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140031
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140032
  shape_item_guid: 120005
  color_item_guid: 130002
- hilt_item_guid: 140033
  shape_item_guid: 120005
  color_item_guid: 130000
- hilt_item_guid: 140034
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140035
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140036
  shape_item_guid: 120000
  color_item_guid: 130000
- hilt_item_guid: 140037
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 140038
  shape_item_guid: 120007
  color_item_guid: 130004
- hilt_item_guid: 140039
  shape_item_guid: 120007
  color_item_guid: 130012
- hilt_item_guid: 140040
  shape_item_guid: 120008
  color_item_guid: 130001
- hilt_item_guid: 140041
  shape_item_guid: 120009
  color_item_guid: 130007
- hilt_item_guid: 140042
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140043
  shape_item_guid: 120003
  color_item_guid: 130007
- hilt_item_guid: 140044
  shape_item_guid: 120009
  color_item_guid: 130004
- hilt_item_guid: 140045
  shape_item_guid: 120014
  color_item_guid: 130001
- hilt_item_guid: 140046
  shape_item_guid: 120000
  color_item_guid: 130001
- hilt_item_guid: 140047
  shape_item_guid: 120019
  color_item_guid: 130001
- hilt_item_guid: 230098
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 230099
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 230100
  shape_item_guid: 90000
  color_item_guid: 100004
- hilt_item_guid: 230101
  shape_item_guid: 120000
  color_item_guid: 130004
- hilt_item_guid: 230102
  shape_item_guid: 120000
  color_item_guid: 130004
