---
# AT-RT
- id: 1
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 1940
  texture: ATRT
  name_id: 60025
  icon_set_id: 2487
  mount_composite_effect: 2696
  dismount_composite_effect: 2697
# AT-RT Snow Camo
- id: 2
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 1940
  texture: SnowCamo
  name_id: 52573
  icon_set_id: 3041
  mount_composite_effect: 2696
  dismount_composite_effect: 2697
# BARC Green
- id: 3
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2264
  texture: BasicGreen
  name_id: 4811
  icon_set_id: 2695
  mount_composite_effect: 2755
  dismount_composite_effect: 2756
# BARC Red
- id: 4
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2264
  texture: MustafarRed
  name_id: 4621
  icon_set_id: 2696
  mount_composite_effect: 2755
  dismount_composite_effect: 2756
# BARC Blue
- id: 5
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2264
  texture: UmbaranBlue
  name_id: 50805
  icon_set_id: 2697
  mount_composite_effect: 2755
  dismount_composite_effect: 2756
# Mando White
- id: 6
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2394
  texture: MandalorianWhiteBlue
  name_id: 4869
  icon_set_id: 2920
  mount_composite_effect: 2797
  dismount_composite_effect: 2798
# Mando Purple
- id: 7
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2394
  texture: CoruscantPurple
  name_id: 51372
  icon_set_id: 3068
  mount_composite_effect: 2797
  dismount_composite_effect: 2798
# Mando Camo
- id: 8
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2394
  texture: Kashyyyk
  name_id: 51374
  icon_set_id: 2954
  mount_composite_effect: 2797
  dismount_composite_effect: 2798
# Mando Blue
- id: 9
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2394
  texture: SOE
  name_id: 51370
  icon_set_id: 2920
  mount_composite_effect: 2797
  dismount_composite_effect: 2798
# FC20 Blood
- id: 10
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2457
  texture: Bloodfin
  name_id: 51937
  icon_set_id: 3043
  mount_composite_effect: 2815
  dismount_composite_effect: 2816
# FC20 Sith
- id: 11
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2457
  texture: Sith
  name_id: 52569
  icon_set_id: 3039
  mount_composite_effect: 2815
  dismount_composite_effect: 2816
# Tauntaun
- id: 12
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2487
  texture: Gray
  name_id: 52571
  icon_set_id: 3040
  mount_composite_effect: 2820
  dismount_composite_effect: 2821
# Bantha
- id: 13
  speed_multiplier: 0.5
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2489
  texture: Bantha
  name_id: 52581
  icon_set_id: 3042
  mount_composite_effect: 2832
  dismount_composite_effect: 2833
# Narglatch Blue
- id: 14
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2534
  texture: Blue
  name_id: 52849
  icon_set_id: 3080
  mount_composite_effect: 2996
  dismount_composite_effect: 2997
# Narglatch Maroon
- id: 15
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2534
  texture: Red
  name_id: 60763
  icon_set_id: 3844
  mount_composite_effect: 2996
  dismount_composite_effect: 2997
# Narglatch Brown (Red Icon)
- id: 16
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2534
  texture: Brown
  name_id: 16549
  icon_set_id: 2952
  mount_composite_effect: 2996
  dismount_composite_effect: 2997
# Narglatch Green
- id: 17
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2534
  texture: Dark
  name_id: 16549
  icon_set_id: 3132
  mount_composite_effect: 2996
  dismount_composite_effect: 2997
# 74-Z Blue
- id: 18
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2604
  texture: 74ZBlue
  name_id: 53524
  icon_set_id: 3201
  mount_composite_effect: 2857
  dismount_composite_effect: 2858
# 74-Z Tan
- id: 19
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2604
  texture: 74ZSand
  name_id: 53522
  icon_set_id: 3200
  mount_composite_effect: 2857
  dismount_composite_effect: 2858
# 74-Z White
- id: 20
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2604
  texture: 74ZWhite
  name_id: 53520
  icon_set_id: 3199
  mount_composite_effect: 2857
  dismount_composite_effect: 2858
# Zephyr Green
- id: 21
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2620
  texture: ZephyrGreen
  name_id: 53979
  icon_set_id: 3263
  mount_composite_effect: 2847
  dismount_composite_effect: 2848
# Zephyr Flame
- id: 22
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2620
  texture: ZephyrRedFlame
  name_id: 53978
  icon_set_id: 3262
  mount_composite_effect: 2847
  dismount_composite_effect: 2848
# Zephyr Rust
- id: 23
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2620
  texture: ZephyrRust
  name_id: 53977
  icon_set_id: 3261
  mount_composite_effect: 2847
  dismount_composite_effect: 2848
# Starhawk Black
- id: 24
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2642
  texture: StarhawkBlack
  name_id: 54065
  icon_set_id: 3308
  mount_composite_effect: 2880
  dismount_composite_effect: 2882
# Starhawk Blue
- id: 25
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2642
  texture: StarhawkBlue
  name_id: 54067
  icon_set_id: 3309
  mount_composite_effect: 2880
  dismount_composite_effect: 2882
# Starhawk Brown
- id: 26
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2642
  texture: StarhawkTribal
  name_id: 54069
  icon_set_id: 3310
  mount_composite_effect: 2880
  dismount_composite_effect: 2882
# Tauntaun Holiday
- id: 27
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2643
  texture: White
  name_id: 54076
  icon_set_id: 3312
  mount_composite_effect: 2820
  dismount_composite_effect: 2821
# Rancor Brown
- id: 28
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2693
  texture: Brown
  name_id: 50492
  icon_set_id: 2587
  mount_composite_effect: 2888
  dismount_composite_effect: 2889
# Rancor Zanbar
- id: 29
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2693
  texture: Zanbar
  name_id: 54205
  icon_set_id: 3654
  mount_composite_effect: 2888
  dismount_composite_effect: 2889
# Grievous Speeder
- id: 30
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2751
  texture: GrievousSpeeder
  name_id: 60252
  icon_set_id: 3704
  mount_composite_effect: 2994
  dismount_composite_effect: 2995
# Brezak
- id: 31
  speed_multiplier: 1.5625
  jump_height_multiplier: 2
  gravity_multiplier: 0.25
  model_id: 2793
  texture: Brezak
  name_id: 60647
  icon_set_id: 3789
  mount_composite_effect: 3008
  dismount_composite_effect: 3009
# Brezak Green
- id: 32
  speed_multiplier: 1.5625
  jump_height_multiplier: 2
  gravity_multiplier: 0.25
  model_id: 2793
  texture: Teal
  name_id: 60776
  icon_set_id: 3860
  mount_composite_effect: 3008
  dismount_composite_effect: 3009
# STAP
- id: 33
  speed_multiplier: 1.5625
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2821
  texture: STAP
  name_id: 43028
  icon_set_id: 3826
  mount_composite_effect: 3011
  dismount_composite_effect: 3012
# Fambaa
- id: 34
  speed_multiplier: 0.5
  jump_height_multiplier: 1
  gravity_multiplier: 1
  model_id: 2823
  texture: Fambaa
  name_id: 60759
  icon_set_id: 3843
  mount_composite_effect: 3013
  dismount_composite_effect: 3014
