umbara:
  guid: 10
  max_players: 4294967295
  template_name: 10635
  asset_name: Combat_Umbara_South_01
  hide_ui: false
  is_combat: true
  default_point_of_interest:
    guid: 19
    pos:
      x: 69
      y: 1.9294561
      z: 38
      w: 1
    rot:
      x: 0.5
      y: 0
      z: 0.85
      w: 0
    name_id: 50654
  speed: 8
  jump_height_multiplier: 1
  gravity_multiplier: 1
  seconds_per_day: 10800
  map_id: 104
